const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Touch,
		C3.Plugins.Sprite,
		C3.Plugins.Browser,
		C3.Behaviors.Tween,
		C3.Plugins.Arr,
		C3.Plugins.AJAX,
		C3.Plugins.Json,
		C3.Plugins.Audio,
		C3.Plugins.Text,
		C3.Behaviors.Flash,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Browser.Acts.GoToURL,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.Arr.Acts.Delete,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Arr.Acts.Shuffle,
		C3.Plugins.System.Acts.CreateObjectByName,
		C3.Plugins.Json.Exps.Get,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Arr.Cnds.CompareSize,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Acts.GoToLayout
	];
};
self.C3_JsPropNameTable = [
	{Touch: 0},
	{refreshBtn: 0},
	{audioBtn: 0},
	{shareBtn: 0},
	{fullScreenBtn: 0},
	{Browser: 0},
	{loaderEmpty: 0},
	{Tween: 0},
	{loaderFill: 0},
	{loaderLogo: 0},
	{arkaplan: 0},
	{üstbar: 0},
	{molekulTitle: 0},
	{isActive: 0},
	{nextBtn: 0},
	{prevBtn: 0},
	{answerID: 0},
	{apolarBtn: 0},
	{suBtn: 0},
	{iyonikBtn: 0},
	{karbonBtn: 0},
	{polarBtn: 0},
	{molekul0: 0},
	{molekul1: 0},
	{molekul2: 0},
	{molekul3: 0},
	{molekul4: 0},
	{molekul5: 0},
	{molekul7: 0},
	{molekul8: 0},
	{molekul9: 0},
	{molekul10: 0},
	{molekul11: 0},
	{molekul6: 0},
	{randomArray: 0},
	{AJAX: 0},
	{polarJSON: 0},
	{Audio: 0},
	{Flash: 0},
	{Text: 0},
	{bagBtn: 0},
	{cozunmeBtn: 0},
	{molekuller: 0},
	{molekulPosX: 0},
	{molekulPosY: 0},
	{bagControl: 0},
	{cozunmeControl: 0},
	{answerUID: 0},
	{isLoader: 0}
];

self.InstanceType = {
	Touch: class extends self.IInstance {},
	refreshBtn: class extends self.ISpriteInstance {},
	audioBtn: class extends self.ISpriteInstance {},
	shareBtn: class extends self.ISpriteInstance {},
	fullScreenBtn: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	loaderEmpty: class extends self.ISpriteInstance {},
	loaderFill: class extends self.ISpriteInstance {},
	loaderLogo: class extends self.ISpriteInstance {},
	arkaplan: class extends self.ISpriteInstance {},
	üstbar: class extends self.ISpriteInstance {},
	molekulTitle: class extends self.ISpriteInstance {},
	nextBtn: class extends self.ISpriteInstance {},
	prevBtn: class extends self.ISpriteInstance {},
	apolarBtn: class extends self.ISpriteInstance {},
	suBtn: class extends self.ISpriteInstance {},
	iyonikBtn: class extends self.ISpriteInstance {},
	karbonBtn: class extends self.ISpriteInstance {},
	polarBtn: class extends self.ISpriteInstance {},
	molekul0: class extends self.ISpriteInstance {},
	molekul1: class extends self.ISpriteInstance {},
	molekul2: class extends self.ISpriteInstance {},
	molekul3: class extends self.ISpriteInstance {},
	molekul4: class extends self.ISpriteInstance {},
	molekul5: class extends self.ISpriteInstance {},
	molekul7: class extends self.ISpriteInstance {},
	molekul8: class extends self.ISpriteInstance {},
	molekul9: class extends self.ISpriteInstance {},
	molekul10: class extends self.ISpriteInstance {},
	molekul11: class extends self.ISpriteInstance {},
	molekul6: class extends self.ISpriteInstance {},
	randomArray: class extends self.IArrayInstance {},
	AJAX: class extends self.IInstance {},
	polarJSON: class extends self.IJSONInstance {},
	Audio: class extends self.IInstance {},
	Text: class extends self.ITextInstance {},
	bagBtn: class extends self.ISpriteInstance {},
	cozunmeBtn: class extends self.ISpriteInstance {},
	molekuller: class extends self.ISpriteInstance {}
}